//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleados> EmpleadosSet { get; set; }
        public virtual DbSet<Departamentos> DepartamentosSet { get; set; }
        public virtual DbSet<Cargos> CargosSet { get; set; }
        public virtual DbSet<Nominas> NominasSet { get; set; }
        public virtual DbSet<Salidas> SalidasSet { get; set; }
        public virtual DbSet<Vacaciones> VacacionesSet { get; set; }
        public virtual DbSet<Permisos> PermisosSet { get; set; }
        public virtual DbSet<Licencias> LicenciasSet { get; set; }
    }
}
